# Generated by Django 4.1.4 on 2023-01-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('from_location', models.CharField(max_length=20)),
                ('to_location', models.CharField(max_length=20)),
                ('leaving_with', models.IntegerField()),
                ('date_time_of_leaving', models.DateTimeField()),
                ('number_of_bags', models.IntegerField()),
                ('estimated_kms', models.IntegerField()),
                ('willing_to_pay', models.FloatField()),
            ],
        ),
    ]
