# Generated by Django 4.1.4 on 2023-01-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lift', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lift',
            name='first_name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='lift',
            name='last_name',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
