# Generated by Django 4.1.4 on 2023-01-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lift', '0002_lift_first_name_lift_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lift',
            name='from_location',
            field=models.CharField(choices=[('Cape Town', 'Cape Town'), ('Stellenbosch', 'Stellenbosch'), ('Aggeneys', 'Aggeneys'), ('Pofadder', 'Pofadder')], default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='lift',
            name='to_location',
            field=models.CharField(choices=[('Cape Town', 'Cape Town'), ('Stellenbosch', 'Stellenbosch'), ('Aggeneys', 'Aggeneys'), ('Pofadder', 'Pofadder')], default=None, max_length=300),
        ),
    ]
